name: Clear Directory Before Check Workflow

on:
  workflow_dispatch:
  workflow_call:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clean up directory
        run: |
          rm -rf /project/src/test/java/hexlet/project/*